import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

/**
 * Next's own rules, which is the set worth having here: they catch the
 * mistakes this codebase can actually make, such as an <a> where a <Link>
 * belongs, or an <img> that should be next/image.
 *
 * The Supabase edge function is Deno and is linted by nothing here, the same
 * reason tsconfig excludes it.
 */
const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is generated by Next and gitignored, so its contents are
    // not ours to satisfy.
    ignores: ['.next/**', 'out/**', 'node_modules/**', 'supabase/**', 'next-env.d.ts'],
  },
];

export default config;
